# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

trigger:
    - master

pr:
    - master
    
pool:
  vmImage: 'vs2017-win2016'
    
steps:

- task: Npm@1
  inputs:
    command: 'install'

- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'run test'